USE freelancer_marketplace;

CREATE TABLE IF NOT EXISTS fields (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    icon VARCHAR(60) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO fields (name, icon) VALUES
('Software Development', 'fa-solid fa-code'),
('Web Development', 'fa-solid fa-globe'),
('Mobile App Development', 'fa-solid fa-mobile-screen'),
('Graphic Design', 'fa-solid fa-palette'),
('UI/UX Design', 'fa-solid fa-pen-ruler'),
('Data Science', 'fa-solid fa-chart-line'),
('Data Entry', 'fa-solid fa-keyboard'),
('Digital Marketing', 'fa-solid fa-bullhorn'),
('SEO Specialist', 'fa-solid fa-magnifying-glass-chart'),
('Content Writing', 'fa-solid fa-pen'),
('Copywriting', 'fa-solid fa-feather'),
('Translation', 'fa-solid fa-language'),
('Video Editing', 'fa-solid fa-film'),
('Photography', 'fa-solid fa-camera'),
('Animation', 'fa-solid fa-wand-magic-sparkles'),
('Voice Over', 'fa-solid fa-microphone'),
('Music Production', 'fa-solid fa-music'),
('Accounting', 'fa-solid fa-calculator'),
('Bookkeeping', 'fa-solid fa-book'),
('Legal Services', 'fa-solid fa-gavel'),
('Nursing', 'fa-solid fa-user-nurse'),
('Medicine / Doctors', 'fa-solid fa-stethoscope'),
('Dentistry', 'fa-solid fa-tooth'),
('Pharmacy', 'fa-solid fa-prescription-bottle-medical'),
('Physiotherapy', 'fa-solid fa-dumbbell'),
('Mental Health Counseling', 'fa-solid fa-brain'),
('Nutrition & Dietetics', 'fa-solid fa-apple-whole'),
('Fitness Training', 'fa-solid fa-heart-pulse'),
('Teaching / Tutoring', 'fa-solid fa-chalkboard-user'),
('Civil Engineering', 'fa-solid fa-helmet-safety'),
('Electrical Engineering', 'fa-solid fa-bolt'),
('Mechanical Engineering', 'fa-solid fa-gears'),
('Architecture', 'fa-solid fa-drafting-compass'),
('Interior Design', 'fa-solid fa-couch'),
('Fashion Design', 'fa-solid fa-shirt'),
('Beauty & Cosmetology', 'fa-solid fa-spa'),
('Hair Styling', 'fa-solid fa-scissors'),
('Event Planning', 'fa-solid fa-calendar-check'),
('Catering & Culinary', 'fa-solid fa-utensils'),
('Real Estate', 'fa-solid fa-house'),
('Sales', 'fa-solid fa-handshake'),
('Customer Service', 'fa-solid fa-headset'),
('Human Resources', 'fa-solid fa-users'),
('Project Management', 'fa-solid fa-diagram-project'),
('Virtual Assistance', 'fa-solid fa-laptop'),
('Cybersecurity', 'fa-solid fa-shield-halved'),
('IT Support / Networking', 'fa-solid fa-network-wired'),
('Agriculture', 'fa-solid fa-tractor'),
('Logistics & Delivery', 'fa-solid fa-truck'),
('Construction & Trades', 'fa-solid fa-hammer'),
('Driving Services', 'fa-solid fa-car');

ALTER TABLE freelancers ADD COLUMN field_id INT DEFAULT NULL;
ALTER TABLE freelancers ADD CONSTRAINT fk_freelancer_field FOREIGN KEY (field_id) REFERENCES fields(id) ON DELETE SET NULL;